spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team2_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: always
---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team2_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bani
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
