server:
  port: 8080
spring:
  profiles:
    active: local
  config:
    import: classpath:application-db.yaml, classpath:application-key.yaml

cache:
  ttl: 10s
  size: 100

jwt:
  secret-key: TFRsGRu_d3UWp-WpoHShC_uHQy86Sp1rYX403NBibcw

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    #    tags-sorter: alpha
    #    operations-sorter: alpha
    display-request-duration: true
  paths-to-exclude:
    - /test/**

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      accessKey: S3_ACCESS_KEY
      secretKey: S3_SECRET_KEY
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: team2-server-s3
