server:
  port: 8080
spring:
  profiles:
    active: local
  config:
    import: classpath:application-db.yaml, classpath:application-key.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cache:
  ttl: 10s
  size: 100

jwt:
  secret-key: TFRsGRu_d3UWp-WpoHShC_uHQy86Sp1rYX403NBibcw

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    #    tags-sorter: alpha
    #    operations-sorter: alpha
    display-request-duration: true
  paths-to-exclude:
    - /test/**

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: trace

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: team2-server-s3
