spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/team2_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: test
  jpa:
    defer-datasource-initialization: true
---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team2_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ??
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
