server:
  port: 8080
spring:
  profiles:
    active: local
  config:
    import: classpath:application-db.yaml

cache:
  ttl: 10s
  size: 100

jwt:
  secret-key: TFRsGRu_d3UWp-WpoHShC_uHQy86Sp1rYX403NBibcw

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
#    tags-sorter: alpha
#    operations-sorter: alpha
    display-request-duration: true
  paths-to-exclude:
  - /channel/**
  - /user/**
  - /test/**

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
