package com.wafflestudio.team2server.common.error

import org.springframework.http.HttpStatus

enum class ErrorType(
	val code: Int,
	val httpStatus: HttpStatus,
) {
	// 400
	INVALID_PARAMETER(10001, HttpStatus.BAD_REQUEST),
	EMAIL_BLANK(10004, HttpStatus.BAD_REQUEST),
	INVALID_AREA_COUNT(10005, HttpStatus.BAD_REQUEST),
	FILE_NOT_AVAILABLE(10006, HttpStatus.BAD_REQUEST),
	BAD_FILE_FORMAT(10007, HttpStatus.BAD_REQUEST),
	INVALID_PROVIDER(10008, HttpStatus.BAD_REQUEST),
	INVALID_CHANNEL_ID(10009, HttpStatus.BAD_REQUEST),
	INVALID_MESSAGE_FORMAT(10010, HttpStatus.BAD_REQUEST),
	INVALID_SESSION(10011, HttpStatus.BAD_REQUEST),
	INVALID_USER_ID(10012, HttpStatus.BAD_REQUEST),
	INVALID_BID_PRICE(10013, HttpStatus.BAD_REQUEST),
	INVALID_DEADLINE(10014, HttpStatus.BAD_REQUEST),

	// 401
	UNAUTHORIZED(11001, HttpStatus.UNAUTHORIZED),
	NO_UID(11002, HttpStatus.UNAUTHORIZED),
	EXPIRED_TOKEN(11003, HttpStatus.UNAUTHORIZED),
	COMEMNT_NOT_MATCHED(11004, HttpStatus.UNAUTHORIZED),
	EXPIRED_AUCTION(11005, HttpStatus.UNAUTHORIZED),

	// 403
	PERMISSION_DENIED(13001, HttpStatus.FORBIDDEN),

	// 404
	USER_NOT_FOUND(14001, HttpStatus.NOT_FOUND),
	AREA_NOT_FOUND(14002, HttpStatus.NOT_FOUND),
	POST_NOT_FOUND(14003, HttpStatus.NOT_FOUND),
	POST_ID_NOT_FOUND(14004, HttpStatus.NOT_FOUND),
	CHANNEL_USER_ID_NOT_FOUND(14005, HttpStatus.NOT_FOUND),
	COMMUNITY_NOT_FOUND(14006, HttpStatus.NOT_FOUND),
	COMMENT_NOT_FOUND(14007, HttpStatus.NOT_FOUND),

	// 409
	EMAIL_ALREADY_EXISTS(19001, HttpStatus.CONFLICT),
	NICKNAME_ALREADY_EXISTS(19002, HttpStatus.CONFLICT),
	PROVIDER_KEY_ALREADY_EXISTS(19003, HttpStatus.CONFLICT),
	ALREADY_PINNED(19004, HttpStatus.CONFLICT),
	NOT_PINNED(19005, HttpStatus.CONFLICT),
	SELF_TRANSACTION(19006, HttpStatus.CONFLICT)
}
